### PR TITLE
Remove useless code from Elliptic Curves Regression

### PR DESCRIPTION
**Pull request by toddr**
I can't determine that this code actually does anything. Looks like it's left over from some old issue??

### CODE REVIEW

**Comment by noxxi** [comment]
Hi,
thank for your patch but could you please explain why I should remove this code. It is clearly shown why the code is there, i.e. see the reference to the OpenSSL ticket.

**Comment by toddr** [comment]
Can you explain what it does? The code:
```perl
( Net::SSLeay::OPENSSL_VERSION_NUMBER() != 0x1000104f || length(pack("P",0)) == 4 );
```
Is a check. I assume this does nothing:
```perl
Net::SSLeay::OPENSSL_VERSION_NUMBER() != 0x1000104f
```

to my knowledge length == 5 seems to do nothing?

**Comment by toddr** [comment]
oh wow. I'm reading this one more time and realizing the problem. There are comments in the middle of the statement to the point I couldn't tell where the statement began and ended.

**Comment by rurban** [comment]
Please close this. The issue is easy to understand.

**Pull request closed without merging**
